### ISSUE TITLE
Molecule masses from symbol issue

### ISSUE THREAD

**Issue by dgasmith** [MolSSI/QCElemental#225]
**Describe the bug**
Nucleon symbols and values are in the periodictable information, but do not propagate their values into a Molecules mass. For example symbol `D` or `He3` do not correctly review masses of 2 or 3, respectively.

**To Reproduce**
```python
>>> qcel.models.Molecule(symbols=["He3"], geometry=[0,0,0]).masses
array([4.00260325413])
```

**Expected behavior**
The mass of the Helium3 to be 3 and change.

**Additional context**
The issues comes from `reconcile_nucleus` where everything is validated off of atomic number rather than the input symbol. This looks like a non trivial fix to that logic.

**Comment by loriab** [comment]
did you try `3He`? that should recognize the isotope. `He3` is read as a user-convenience tag of 3 on regular helium.

**Comment by dgasmith** [comment]
`qcelemental.exceptions.NotAnElementError: 3He`

There are unambiguous issues as well with known isotopes:
```python
>>> qcel.models.Molecule(symbols=["D"], geometry=[0,0,0]).masses
array([1.00782503])
```

**Comment by loriab** [comment]
ok. it's probably in the handing over of field symbol to molparse -- may need a different field. it shouldn't be deep, though, since this is literally the problem reconcile_nucleus was built to handle. https://github.com/MolSSI/QCElemental/blob/master/qcelemental/molparse/nucleus.py#L381

**Comment by loriab** [comment]
the below works (though it's not set up to recognize D, T). understandably you'd like to not have so many guts showing to make a simple deuterium.

```
>>> qcel.models.Molecule(**qcel.molparse.to_schema(qcel.molparse.from_arrays(elbl=["2H"], geom=[0,0,0]), dtype=2)).masses
array([2.01410177812])
```

The problem comes about pretty much because https://github.com/MolSSI/QCElemental/blob/master/qcelemental/molparse/from_schema.py#L82 . https://github.com/MolSSI/QCElemental/blob/master/qcelemental/molparse/from_arrays.py#L191-L195 I hesitate to flip it without really studying the consequences.

**Comment by dgasmith** [comment]
Yea, I don't think this is either a priority or a quick fix. More of a "I was writing a test was and was somewhat surprised". Something to keep in mind I think.

**Comment by loriab** [comment]
I don't know if it's so much a fix as just the current setup enforces schema field definitions. Below are a couple schema-approved ways to do your original problem. Redefining symbols where as input it's a spec label and as output it's a string is a new kettle of fish. But if that is wanted someday, the underlying tech is ready.

```
>>> qcel.models.Molecule(symbols=["He"], mass_numbers=[3], geometry=[0,0,0]).masses
array([3.01602932])
>>> qcel.models.Molecule.from_data("""3He 0 0 0""").masses
array([3.01602932])
```

**Comment by dgasmith** [comment]
In this case perhaps `symbols=["He3"]` should throw an error that information in the symbols is overloaded?

**Comment by loriab** [comment]
Sounds sensible at first. You have hit on an inconsistency, though. speclabel takes prefix mass number so that post can be label or mass, so `3He`. meanwhile, the periodictable takes suffix mass number: `He3`.

So symbols _is_ being broadly interpreted (6 lines below map to the same Mol) but only to extract the info that is properly contained in `symbols`. Probably something like an option on `to_Z(..., strict=True)` that restricts interpretation to element only.

```
# all same
qcel.models.Molecule(symbols=['He'], geometry=[0,0,0])
qcel.models.Molecule(symbols=['He3'], geometry=[0,0,0])
qcel.models.Molecule(symbols=['He4'], geometry=[0,0,0])
qcel.models.Molecule(symbols=['2'], geometry=[0,0,0])
qcel.models.Molecule(symbols=[2], geometry=[0,0,0])
qcel.models.Molecule(symbols=['helium'], geometry=[0,0,0])
# replies "you fool"
qcel.models.Molecule(symbols=['He300'], geometry=[0,0,0])
```
